[package]
name = "consclr"
version = "0.2.2"
edition = "2021"
author = "purplebut"
description = "a rust library to make console text colorful"
license = "MIT"
readme = "README.md"

[dependencies]
cbfr = "0.1.5"

